apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Adds namespace to all resources.
namespace: composable-operator

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: composable-

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

bases:
- config/crd
- config/rbac
- config/manager

images:
- name: composable
  newName: composable

