apiVersion: ibmcloud.ibm.com/v1alpha1
kind: Composable
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: comp
spec:
  template: 
    apiVersion: ibmcloud.ibm.com/v1alpha1
    kind: Service
    metadata:
      name: mymessagehub
      namespace: default
    spec:
      plan: standard
      serviceClass: messagehub